'use strict';

/**
 * BAT-05 — confined, receipted companion output.
 *
 * The writer owns the filesystem half of a completion.  It derives the
 * destination from the canonical source path, writes an exclusive sibling
 * temporary file, fsyncs it, and renames it into place.  Only after rename
 * succeeds does it ask BatchDomain to persist the receipt and mark the job
 * done in one SQLite transaction.  If that transaction fails, the writer
 * removes its new bytes (or restores the prior generated bytes) before
 * returning the error.
 */

const crypto = require('node:crypto');
const fs = require('node:fs');
const path = require('node:path');

const { AppError, createAppError } = require('../../../shared/contracts/errors.ts');
const {
  assertSafePathSyntax,
  resolvePathWithinRoot,
} = require('./folderAccess.js');
const { companionPath } = require('./batchWatcher.js');

const TEMPORARY_PREFIX = '.vaniscript-companion-';
const TEMPORARY_EXTENSIONS = Object.freeze([
  '.tmp',
  '.partial',
  '.part',
  '.crdownload',
  '.download',
]);

function isPlainObject(value) {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function errorDetails(error) {
  return {
    cause: error instanceof Error ? error.message : String(error),
    code: error && typeof error === 'object' && 'code' in error ? error.code : undefined,
  };
}

function normalizeFingerprint(value, field = 'fingerprint') {
  let candidate = value;
  if (typeof candidate === 'string') {
    try {
      candidate = JSON.parse(candidate);
    } catch (error) {
      throw createAppError('VALIDATION_FAILED', `${field} must be a fingerprint object.`, errorDetails(error));
    }
  }
  if (!isPlainObject(candidate)) {
    throw createAppError('VALIDATION_FAILED', `${field} must contain sizeBytes and sha256.`);
  }
  if (!Number.isSafeInteger(candidate.sizeBytes) || candidate.sizeBytes < 0) {
    throw createAppError('VALIDATION_FAILED', `${field}.sizeBytes must be a non-negative safe integer.`);
  }
  if (typeof candidate.sha256 !== 'string' || !/^[0-9a-f]{64}$/i.test(candidate.sha256)) {
    throw createAppError('VALIDATION_FAILED', `${field}.sha256 must be a SHA-256 hex string.`);
  }
  const normalized = { sizeBytes: candidate.sizeBytes, sha256: candidate.sha256.toLowerCase() };
  if (candidate.mtimeMs !== undefined) {
    if (typeof candidate.mtimeMs !== 'number' || !Number.isFinite(candidate.mtimeMs) || candidate.mtimeMs < 0) {
      throw createAppError('VALIDATION_FAILED', `${field}.mtimeMs must be a non-negative number.`);
    }
    normalized.mtimeMs = candidate.mtimeMs;
  }
  return normalized;
}

function sameFingerprint(left, right, includeMtime = false) {
  if (!left || !right) return false;
  if (left.sizeBytes !== right.sizeBytes || left.sha256 !== right.sha256) return false;
  return !includeMtime || left.mtimeMs === right.mtimeMs;
}

function fingerprintBytes(bytes) {
  const data = Buffer.isBuffer(bytes) ? bytes : Buffer.from(bytes);
  return {
    sizeBytes: data.length,
    sha256: crypto.createHash('sha256').update(data).digest('hex'),
  };
}

function statPath(filePath, label = 'Path') {
  let stats;
  try {
    stats = fs.lstatSync(filePath);
  } catch (error) {
    if (error && error.code === 'ENOENT') return null;
    throw createAppError('PERMISSION_DENIED', `Cannot inspect ${label.toLowerCase()} "${filePath}".`, errorDetails(error));
  }
  if (stats.isSymbolicLink()) {
    throw createAppError('PERMISSION_DENIED', `Refusing symlink ${label.toLowerCase()} "${filePath}".`);
  }
  return stats;
}

function fingerprintFile(filePath, label = 'File') {
  const before = statPath(filePath, label);
  if (!before) throw createAppError('NOT_FOUND', `${label} is unavailable: ${filePath}`);
  if (!before.isFile()) throw createAppError('VALIDATION_FAILED', `${label} is not a regular file: ${filePath}`);
  let bytes;
  try {
    bytes = fs.readFileSync(filePath);
  } catch (error) {
    throw createAppError('PERMISSION_DENIED', `Cannot read ${label.toLowerCase()} "${filePath}".`, errorDetails(error));
  }
  const after = statPath(filePath, label);
  if (!after || !after.isFile() || after.size !== before.size || after.mtimeMs !== before.mtimeMs) {
    throw createAppError('SOURCE_CHANGED', `${label} changed while it was being read: ${filePath}`);
  }
  return {
    bytes,
    fingerprint: fingerprintBytes(bytes),
    mtimeMs: before.mtimeMs,
  };
}

function pathFold(value) {
  return String(value).normalize('NFC').toLocaleLowerCase('en-US');
}

function samePath(left, right) {
  return pathFold(path.normalize(left)) === pathFold(path.normalize(right));
}

function isUnsafeOutputName(name) {
  const lower = name.toLowerCase();
  return name.length === 0
    || name.startsWith('.')
    || name.endsWith('~')
    || TEMPORARY_EXTENSIONS.some((extension) => lower.endsWith(extension));
}

function normalizeBytes(value) {
  if (Buffer.isBuffer(value)) return value;
  if (typeof value === 'string') return Buffer.from(value, 'utf8');
  if (value instanceof Uint8Array) return Buffer.from(value);
  throw createAppError('VALIDATION_FAILED', 'Companion content must be a string, Buffer, or Uint8Array.');
}

function isCancelled(request) {
  if (request.signal && request.signal.aborted) return true;
  return typeof request.isCancelled === 'function' && request.isCancelled() === true;
}

function throwIfCancelled(request) {
  if (isCancelled(request)) throw createAppError('CANCELLED', 'Companion output was cancelled.');
}

function allocateTemporaryFile(parent, outputName) {
  for (let attempt = 0; attempt < 8; attempt += 1) {
    const candidate = path.join(
      parent,
      `${TEMPORARY_PREFIX}${outputName}.${process.pid}-${crypto.randomBytes(8).toString('hex')}.tmp`,
    );
    try {
      const fd = fs.openSync(candidate, 'wx', 0o600);
      return { fd, path: candidate };
    } catch (error) {
      if (error && error.code === 'EEXIST') continue;
      if (error && (error.code === 'EACCES' || error.code === 'EPERM')) {
        throw createAppError('PERMISSION_DENIED', `Cannot create companion temporary file in "${parent}".`, errorDetails(error));
      }
      throw createAppError('INTERNAL', `Cannot create companion temporary file in "${parent}".`, errorDetails(error));
    }
  }
  throw createAppError('INTERNAL', 'Could not allocate a unique companion temporary file.');
}

function writeAndSync(fd, bytes, targetPath) {
  try {
    fs.writeFileSync(fd, bytes);
    fs.fsyncSync(fd);
  } catch (error) {
    throw createAppError('INTERNAL', `Atomic companion write failed for "${targetPath}".`, errorDetails(error));
  }
}

function removeIfOwned(filePath, expectedFingerprint) {
  let current;
  try {
    current = statPath(filePath, 'Companion output');
  } catch {
    return;
  }
  if (!current || !current.isFile()) return;
  let currentFingerprint;
  try {
    currentFingerprint = fingerprintFile(filePath, 'Companion output').fingerprint;
  } catch {
    return;
  }
  if (!sameFingerprint(currentFingerprint, expectedFingerprint)) return;
  try {
    fs.unlinkSync(filePath);
  } catch {
    // Cleanup is best effort and must not hide the original failure.
  }
}

function restoreBytes(filePath, bytes) {
  const parent = path.dirname(filePath);
  const outputName = path.basename(filePath);
  const allocated = allocateTemporaryFile(parent, outputName);
  let fd = allocated.fd;
  try {
    writeAndSync(fd, bytes, filePath);
    fs.closeSync(fd);
    fd = null;
    fs.renameSync(allocated.path, filePath);
    allocated.path = null;
  } finally {
    if (fd !== null) {
      try { fs.closeSync(fd); } catch { /* best effort */ }
    }
    if (allocated.path) {
      try { fs.unlinkSync(allocated.path); } catch { /* best effort */ }
    }
  }
}

function readMatchingOutput(parent, outputName) {
  let entries;
  try {
    entries = fs.readdirSync(parent, { withFileTypes: true });
  } catch (error) {
    throw createAppError('PERMISSION_DENIED', `Cannot inspect companion directory "${parent}".`, errorDetails(error));
  }
  const folded = pathFold(outputName);
  const matching = entries
    .filter((entry) => pathFold(entry.name) === folded)
    .sort((left, right) => (left.name === outputName ? -1 : right.name === outputName ? 1 : left.name.localeCompare(right.name)));
  return matching.length > 0 ? path.join(parent, matching[0].name) : null;
}

function inspectOutput(profileRoot, targetPath, outputName, domain) {
  const parent = path.dirname(targetPath);
  const existingPath = readMatchingOutput(parent, outputName);
  const candidatePath = existingPath || targetPath;
  const resolved = resolvePathWithinRoot(profileRoot, candidatePath, { allowMissing: true });
  if (!resolved.exists) {
    return {
      exists: false,
      path: resolved.absolutePath,
      canonicalPath: resolved.canonicalPath,
      bytes: null,
      fingerprint: null,
      receipt: null,
    };
  }
  const stats = statPath(candidatePath, 'Companion output');
  if (!stats.isFile()) {
    throw createAppError('OUTPUT_COLLISION', `Companion output is not a regular file: ${candidatePath}`);
  }
  const inspected = fingerprintFile(candidatePath, 'Companion output');
  const canonicalPath = resolved.canonicalPath;
  const receipt = domain.getOutputReceipt(canonicalPath) || domain.getOutputReceipt(candidatePath);
  return {
    exists: true,
    path: candidatePath,
    canonicalPath,
    bytes: inspected.bytes,
    fingerprint: inspected.fingerprint,
    receipt,
  };
}

function collisionError(outputPath, existingFingerprint) {
  return createAppError(
    'OUTPUT_COLLISION',
    `Companion output already exists and is not a VaniScript-generated file: ${outputPath}`,
    { outputPath, existingFingerprint },
  );
}

function normalizeRequest(raw, fallback = {}) {
  let request = raw;
  if (!isPlainObject(request)) throw createAppError('VALIDATION_FAILED', 'Companion write request must be an object.');
  request = { ...fallback, ...request };
  const job = request.job;
  if (job !== undefined && !isPlainObject(job)) {
    throw createAppError('VALIDATION_FAILED', 'Companion write request job must be an object.');
  }
  const jobId = request.jobId || (job && job.jobId);
  const sourcePath = request.sourcePath || (job && job.sourcePath);
  const profileRoot = request.profileRoot || request.rootPath || request.root;
  const content = request.content !== undefined
    ? request.content
    : request.bytes !== undefined
      ? request.bytes
      : request.data !== undefined
        ? request.data
        : request.text;
  if (typeof jobId !== 'string' || jobId.length === 0) {
    throw createAppError('VALIDATION_FAILED', 'Companion write request jobId is required.');
  }
  if (typeof sourcePath !== 'string' || sourcePath.length === 0) {
    throw createAppError('VALIDATION_FAILED', 'Companion write request sourcePath is required.');
  }
  if (typeof profileRoot !== 'string' || profileRoot.length === 0) {
    throw createAppError('VALIDATION_FAILED', 'Companion write request profileRoot is required.');
  }
  if (content === undefined) throw createAppError('VALIDATION_FAILED', 'Companion content is required.');
  return {
    ...request,
    job,
    jobId,
    sourcePath,
    profileRoot,
    content: normalizeBytes(content),
  };
}

class BatchCompanionWriter {
  constructor(options = {}) {
    if (!isPlainObject(options)) options = {};
    this.domain = options.domain || null;
    this.beforeCommit = typeof options.beforeCommit === 'function' ? options.beforeCommit : null;
    this.beforeReceipt = typeof options.beforeReceipt === 'function' ? options.beforeReceipt : null;
  }

  write(rawRequest, options = {}) {
    const request = normalizeRequest(rawRequest, {
      domain: this.domain,
      beforeCommit: this.beforeCommit,
      beforeReceipt: this.beforeReceipt,
      ...options,
    });
    const domain = request.domain || this.domain;
    if (!domain || typeof domain.getJob !== 'function' || typeof domain.completeJobWithOutputReceipt !== 'function') {
      throw createAppError('VALIDATION_FAILED', 'BatchCompanionWriter requires a BatchDomain receipt API.');
    }

    const job = request.job || domain.getJob(request.jobId);
    if (job.jobId !== request.jobId) {
      throw createAppError('VALIDATION_FAILED', 'Companion write jobId does not match the supplied job.');
    }
    const sourcePath = request.sourcePath;
    const root = resolvePathWithinRoot(request.profileRoot, request.profileRoot).rootPath;
    const source = resolvePathWithinRoot(root, sourcePath);
    const sourceStats = statPath(source.canonicalPath, 'Source');
    if (!sourceStats || !sourceStats.isFile()) {
      throw createAppError('NOT_FOUND', `Source is not a regular file: ${source.canonicalPath}`);
    }

    const targetCandidate = companionPath(source.canonicalPath);
    const derived = resolvePathWithinRoot(root, targetCandidate, { allowMissing: true });
    // Resolve the sibling once up front.  All persisted/output comparisons use
    // this realpath-canonical path so macOS aliases such as /var -> /private/var
    // cannot make the same confined file appear to be a different destination.
    const outputName = path.basename(derived.canonicalPath);
    if (isUnsafeOutputName(outputName)) {
      throw createAppError('PERMISSION_DENIED', `Companion output name is hidden or temporary: ${outputName}`);
    }
    if (samePath(source.canonicalPath, derived.canonicalPath)) {
      throw createAppError('PERMISSION_DENIED', 'Companion output must not equal the source path.');
    }
    if (request.outputPath !== undefined && request.outputPath !== null) {
      assertSafePathSyntax(request.outputPath, 'outputPath');
      const supplied = resolvePathWithinRoot(root, request.outputPath, { allowMissing: true });
      if (!samePath(supplied.canonicalPath, derived.canonicalPath)) {
        throw createAppError('PERMISSION_DENIED', 'Companion outputPath must be the derived sibling .txt path.');
      }
    }
    if (job.outputPath !== null && job.outputPath !== undefined) {
      assertSafePathSyntax(job.outputPath, 'job.outputPath');
      const persisted = resolvePathWithinRoot(root, job.outputPath, { allowMissing: true });
      if (!samePath(persisted.canonicalPath, derived.canonicalPath)) {
        throw createAppError('PERMISSION_DENIED', 'Persisted job outputPath is not the derived sibling .txt path.');
      }
    }

    const expectedSource = request.expectedSourceFingerprint === undefined
      ? job.sourceFingerprint
      : request.expectedSourceFingerprint;
    const initialSource = fingerprintFile(source.canonicalPath, 'Source');
    if (expectedSource !== null && expectedSource !== undefined
      && !sameFingerprint(initialSource.fingerprint, normalizeFingerprint(expectedSource, 'expectedSourceFingerprint'))) {
      throw createAppError('SOURCE_CHANGED', `Source fingerprint changed before companion write: ${source.canonicalPath}`);
    }

    throwIfCancelled(request);
    let inspection = inspectOutput(root, derived.absolutePath, outputName, domain);
    if (inspection.exists && inspection.bytes.length > 0
      && !(inspection.receipt && sameFingerprint(inspection.fingerprint, inspection.receipt.outputFingerprint))) {
      const error = collisionError(inspection.canonicalPath, inspection.fingerprint);
      domain.blockOutputCollision(request.jobId, error.message);
      throw error;
    }

    const bytes = request.content;
    const outputFingerprint = fingerprintBytes(bytes);
    let previousBytes = inspection.exists ? inspection.bytes : null;
    const commitPath = inspection.path;
    let tempPath = null;
    let fd = null;
    let renamed = false;
    let receiptCommitted = false;
    try {
      const allocated = allocateTemporaryFile(path.dirname(commitPath), path.basename(commitPath));
      tempPath = allocated.path;
      fd = allocated.fd;
      writeAndSync(fd, bytes, commitPath);
      fs.closeSync(fd);
      fd = null;
      tempPath = allocated.path;

      if (typeof request.beforeCommit === 'function') request.beforeCommit({ job, outputPath: commitPath });
      throwIfCancelled(request);
      const finalSource = fingerprintFile(source.canonicalPath, 'Source');
      if (!sameFingerprint(finalSource.fingerprint, initialSource.fingerprint, false)
        || (expectedSource !== null && expectedSource !== undefined
          && !sameFingerprint(finalSource.fingerprint, normalizeFingerprint(expectedSource, 'expectedSourceFingerprint')))) {
        throw createAppError('SOURCE_CHANGED', `Source changed before companion commit: ${source.canonicalPath}`);
      }

      inspection = inspectOutput(root, derived.absolutePath, outputName, domain);
      if (inspection.exists && inspection.bytes.length > 0
        && !(inspection.receipt && sameFingerprint(inspection.fingerprint, inspection.receipt.outputFingerprint))) {
        const error = collisionError(inspection.canonicalPath, inspection.fingerprint);
        domain.blockOutputCollision(request.jobId, error.message);
        throw error;
      }
      // Rebase compensation on the last pre-rename observation. This keeps a
      // concurrently-created zero-byte output in the "prior output" branch.
      previousBytes = inspection.exists ? inspection.bytes : null;
      const latestPath = inspection.path;
      if (latestPath !== commitPath) throw createAppError('OUTPUT_COLLISION', 'Companion output path changed during commit.');
      const latestStats = statPath(commitPath, 'Companion output');
      if (latestStats && latestStats.isSymbolicLink()) {
        throw createAppError('PERMISSION_DENIED', `Refusing symlink companion output "${commitPath}".`);
      }
      fs.renameSync(tempPath, commitPath);
      tempPath = null;
      renamed = true;

      if (typeof request.beforeReceipt === 'function') request.beforeReceipt({ job, outputPath: inspection.canonicalPath });
      throwIfCancelled(request);
      const completed = domain.completeJobWithOutputReceipt(request.jobId, {
        outputPath: inspection.canonicalPath,
        outputFingerprint,
      });
      receiptCommitted = true;
      return {
        disposition: previousBytes === null ? 'created' : 'replacedGenerated',
        outputPath: inspection.canonicalPath,
        outputFingerprint,
        outputFingerprintToken: JSON.stringify(outputFingerprint),
        receipt: completed.receipt,
        job: completed.job,
      };
    } catch (error) {
      // A rename is provisional until completeJobWithOutputReceipt commits.
      // On cancellation/failure, always remove the temporary file in finally;
      // remove the renamed output only when this job had no prior output and
      // the bytes still match this attempt, otherwise restore the prior
      // generated bytes only when they are still ours.  A user replacement is
      // never clobbered during compensation.
      if (renamed && !receiptCommitted) {
        let current;
        try {
          current = statPath(commitPath, 'Companion output');
        } catch {
          current = null;
        }
        if (current && current.isFile()) {
          if (previousBytes === null) removeIfOwned(commitPath, outputFingerprint);
          else {
            try {
              const currentFingerprint = fingerprintFile(commitPath, 'Companion output').fingerprint;
              if (sameFingerprint(currentFingerprint, outputFingerprint)) restoreBytes(commitPath, previousBytes);
            } catch {
              // Preserve a user replacement rather than clobbering it.
            }
          }
        }
      }
      if (error instanceof AppError) throw error;
      if (error && (error.code === 'EACCES' || error.code === 'EPERM')) {
        throw createAppError('PERMISSION_DENIED', `Companion output failed for "${commitPath}".`, errorDetails(error));
      }
      if (error && error.code === 'ENOENT') {
        throw createAppError('NOT_FOUND', `Companion output path disappeared: ${commitPath}`, errorDetails(error));
      }
      throw createAppError('INTERNAL', `Companion output failed for "${commitPath}".`, errorDetails(error));
    } finally {
      if (fd !== null) {
        try { fs.closeSync(fd); } catch { /* best effort */ }
      }
      if (tempPath) {
        try { fs.unlinkSync(tempPath); } catch { /* best effort */ }
      }
    }
  }
}

function createBatchCompanionWriter(options) {
  return new BatchCompanionWriter(options);
}

function writeCompanion(request, options) {
  return new BatchCompanionWriter(options).write(request);
}

module.exports = {
  BatchCompanionWriter,
  TEMPORARY_PREFIX,
  companionPath,
  createBatchCompanionWriter,
  fingerprintBytes,
  fingerprintFile,
  writeCompanion,
};
